spring:
  application:
    name: backend

  # log color setting
  output:
    ansi:
      enabled: ALWAYS

  # form-data file maxinum size
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB


  # PostgreSQL Driver Setting
  datasource:
    url: jdbc:postgresql://localhost:5432/project_lamp
    username: lamp_backend
    password: lampofhambak0302
    driver-class-name: org.postgresql.Driver

  # JPA Setting
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false

  #LocalStack S3
  cloud:
    aws:
      region: us-east-1
      endpoint: http://localhost:4566
      s3:
        path-style-access-enabled: true
        bucket: project-lamp
        folder:
          document: documents/
          photo: photos/
      credentials:
        access-key: test
        secret-key: test


logging.level.org.younginhambak.backend: DEBUG









